default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: dpg-chsftn5269vdk4mtdph0-a.oregon-postgres.render.com
  port: 5432
  database: doosti
  username: admin
  password: 1Hv8Kq6fBBwlKEMPQOlmKb92GphIHDW7

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
